#!/usr/bin/env python3
"""Generate a search index JS file for the static site.

This script recursively walks the project directory, finds HTML files
(excluding `search.html`), extracts the <title> and visible text, then
writes a JS file that populates `window.embeddedSearchIndex` as proper JSON.

Run it whenever you add or modify pages. The output is written to
`assets/data/search-index.js`.
"""
import os
import re
import json

ROOT = os.getcwd()
OUTPUT = os.path.join(ROOT, 'assets', 'data', 'search-index.js')
EXCLUDE = {'search.html', 'search-en.html'}
SKIP_DIRS = {'.git', 'node_modules', '__pycache__'}

def discover_html_files(root):
    files = []
    for dirpath, dirnames, filenames in os.walk(root):
        # prune dirs we don't want to scan
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            if not fn.endswith('.html'):
                continue
            if fn in EXCLUDE:
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace(os.path.sep, '/')
            files.append(rel)
    return sorted(files)

def extract_text_from_html(path):
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    # title
    m = re.search(r'<title>(.*?)</title>', text, re.IGNORECASE | re.DOTALL)
    title = m.group(1).strip() if m else path
    # preserve img alt text before stripping tags
    text = re.sub(
        r'<img[^>]*\balt=(["\'])(.*?)\1[^>]*>',
        lambda m: f" {m.group(2)} ",
        text,
        flags=re.DOTALL | re.IGNORECASE,
    )
    # remove script/style blocks
    text = re.sub(r'<script[^>]*>.*?</script>', ' ', text, flags=re.DOTALL|re.IGNORECASE)
    text = re.sub(r'<style[^>]*>.*?</style>', ' ', text, flags=re.DOTALL|re.IGNORECASE)
    # strip tags
    content = re.sub(r'<[^>]+>', ' ', text)
    content = re.sub(r'\s+', ' ', content).strip()
    return title, content

def main():
    html_files = discover_html_files(ROOT)
    entries = []
    for rel in html_files:
        path = os.path.join(ROOT, rel)
        try:
            title, content = extract_text_from_html(path)
            entries.append({'url': rel, 'title': title, 'content': content})
        except Exception as e:
            print(f'warning: failed to process {rel}: {e}')

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('/* this file is generated by scripts/build_index.py */\n')
        f.write('window.embeddedSearchIndex = ')
        f.write(json.dumps(entries, ensure_ascii=False))
        f.write(';\n')

    print(f'Produced {OUTPUT} with {len(entries)} entries.')

if __name__ == '__main__':
    main()
